name: pipeline

on: [push]
env:
  APPLICATION_NAME: mywebapp
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: PYTHON ENVIRONMENT SETUP
      uses: actions/setup-python@v1.1.1
    - name: INSTALLING REQUIREMENTS
      run: pip install --quiet --requirement requirements.txt
    - name: Lint code
      run: |
        flake8 --ignore=E501, E231 *.py
        pylint --disable=C0301 --disable=C0326 *.py
    - name: RUNNING UNIT TESTS
      run: |
        python -m unittest --verbose --failfast
