name: pipeline

on: [push]
env:
  APPLICATION_NAME: mywebapp
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: PYTHON ENVIRONMENT SETUP
      uses: actions/setup-python@v1.1.1
    - name: INSTALLING REQUIREMENTS
      run: pip install --quiet --requirement requirements.txt
    - name: Lint code
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 --disable=C0326 *.py
    - name: RUNNING UNIT TESTS
      run: |
        python -m unittest --verbose --failfast

  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: SETTING UP GOOGLE CLOUD
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '274.0.1'
          service_account_email: ${{secrets.GCP_SERVICE_ACCT_EMAIL}}
          service_account_key: ${{secrets.GCP_SERVICE_ACCT_KEY}}
        
      - run: |
          gcloud config set project ${{secrets.GCP_PROJECT_ID}}
          gcloud config set run/region ${{secrets.GCP_REGION}}
          gcloud auth configure-docker
          gcloud info
          
      - name: BUILD AND TAG build-image
        run: docker build -t "gcr.io/${{secrets.GCP_PROJECT_ID}}/${{env.APPLICATION_NAME}}:latest"
      - name: PUBLISH TO GCP IMAGE REGISTRY
        run: docker push gcr.io/${{secrets.GCP_PROJECT_ID}}/${{env.APPLICATION_NAME}}:latest
